// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxb5XESEp9E6KP4Nl_M5mSees5L9t-pFw',
    appId: '1:925899038090:web:dc812fd4e3c3b9abd97c73',
    messagingSenderId: '925899038090',
    projectId: 'memories-f3a84',
    authDomain: 'memories-f3a84.firebaseapp.com',
    storageBucket: 'memories-f3a84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHKZEan8EGiwBSvOIbt3-xvLwFINUDsGw',
    appId: '1:925899038090:android:743f7da200695e91d97c73',
    messagingSenderId: '925899038090',
    projectId: 'memories-f3a84',
    storageBucket: 'memories-f3a84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBancdgsmgx0Qed9vDhnTEg3g9sLQNzepQ',
    appId: '1:925899038090:ios:ff793784516a7ae4d97c73',
    messagingSenderId: '925899038090',
    projectId: 'memories-f3a84',
    storageBucket: 'memories-f3a84.appspot.com',
    androidClientId: '925899038090-dndaravp7erioedo1d2jk1um0v76ifo7.apps.googleusercontent.com',
    iosClientId: '925899038090-oa3ogrb6f5o55q915rujtqa8ibd251tg.apps.googleusercontent.com',
    iosBundleId: 'com.kinn.memories',
  );

}