name: CI/client-web

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "lib/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - "**"
    paths:
      - "lib/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-client-web:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Code Spell Checker
        run: npm install -g cspell

      - name: Check Code Spell
        run: cspell "**/*.{dart,swift,kt}"

      - name: Get Flutter version
        run: |
          asdf_flutter_version="$(cat .tool-versions | awk '{print $2}')"
          flutter_version="$(echo $asdf_flutter_version | sed -e 's/-stable//g')"
          echo "FLUTTER_VERSION=$flutter_version" >> $GITHUB_ENV
      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-${{ env.FLUTTER_VERSION }}
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Install dependencies
        run: flutter pub get
      - name: Generate Code
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Generate env files
        env:
          CLIENT_ENV: ${{ secrets.CLIENT_ENV }}
        run: echo "${CLIENT_ENV}" > env
      - name: Analyze
        run: flutter analyze
    #   - name: Test
    #     run: flutter test
