name: CI/server

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "server/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "server/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  function:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint-not-fix
      - run: npm run cspell
      - run: npm run build
      # - run: npm run test
